/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CustomJewelleryRequest {
  'metal' : string,
  'user' : Principal,
  'style' : string,
  'gemstone' : string,
  'notes' : string,
  'timestamp' : bigint,
  'budget' : bigint,
}
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'user' : Principal,
  'totalAmount' : bigint,
  'timestamp' : bigint,
  'items' : Array<bigint>,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null };
export interface Product {
  'id' : bigint,
  'weight' : number,
  'popularityScore' : bigint,
  'stockQuantity' : bigint,
  'name' : string,
  'craftsmanshipNotes' : string,
  'description' : string,
  'metalType' : string,
  'hallmarkCertified' : boolean,
  'gemstone' : string,
  'category' : ProductCategory,
  'price' : bigint,
  'images' : Array<string>,
}
export type ProductCategory = { 'bangles' : null } |
  { 'bridalSets' : null } |
  { 'traditional' : null } |
  { 'necklaces' : null } |
  { 'earrings' : null } |
  { 'rings' : null };
export interface Review {
  'user' : Principal,
  'productId' : bigint,
  'comment' : string,
  'rating' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[Product], bigint>,
  'addReview' : ActorMethod<[Review], undefined>,
  'addToCart' : ActorMethod<[bigint], undefined>,
  'addToWishlist' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createOrder' : ActorMethod<[], bigint>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'filterByCategory' : ActorMethod<[ProductCategory], Array<Product>>,
  'filterByGemstone' : ActorMethod<[string], Array<Product>>,
  'filterByMetalType' : ActorMethod<[string], Array<Product>>,
  'filterByPriceRange' : ActorMethod<[bigint, bigint], Array<Product>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<bigint>>,
  'getOrderHistory' : ActorMethod<[], Array<Order>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getReviews' : ActorMethod<[bigint], Array<Review>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWishlist' : ActorMethod<[], Array<bigint>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'removeFromCart' : ActorMethod<[bigint], undefined>,
  'removeFromWishlist' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'sortByPopularity' : ActorMethod<[], Array<Product>>,
  'submitCustomRequest' : ActorMethod<[CustomJewelleryRequest], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];